---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.12.9

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2
  - name: windows-2016
    driver_config:
      box: mwrock/Windows2016
  - name: windows-2016-nano
    driver_config:
      box: mwrock/WindowsNano
    provisioner:
      install_msi_url: https://s3-us-west-2.amazonaws.com/nano-chef-client/chef-12.14.60.appx

suites:
  - name: default
    run_list:
      - recipe[windows-hardening::default]
    attributes:
      account_status:
        names:
          - 'Guest'
      rename_account:
        admin_account: false
      security_policy:
        rights:
          SeNetworkLogonRight: '*S-1-1-0, *S-1-5-32-544, *S-1-5-32-545, *S-1-5-32-551'
          SeRemoteInteractiveLogonRight: '*S-1-1-0, *S-1-5-32-544, *S-1-5-32-545, *S-1-5-32-551'
      firewall:
        activate: true
        rules_on: true
        rules: [{'name':'rdp','local_port': 3389,'protocol': 'TCP', 'action': 'allow'},{'name':'winrm','local_port': 5985,'protocol': 'TCP', 'action': 'allow'}]
