---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[windows-hardening::enable_winrm_access]
      - recipe[windows-hardening::default]
    verifier:
      inspec_tests:
<<<<<<< HEAD
        - https://github.com/dev-sec/windows-hardening-benchmark
  
  - name: CIS_2012r2_L1
    run_list:
      - recipe[base-win2012-hardening::CIS_2012r2_L1]
    verifier:
      inspec_tests:
        - test/integration/default 
=======
        - https://github.com/dev-sec/windows-baseline
>>>>>>> upstream/master
