---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012R2
    driver_config:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[windows-hardening::enable_winrm_access]
      - recipe[windows-hardening::default]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-baseline
