name 'base-win2012-hardening'
maintainer 'Joe Gardiner'
maintainer_email 'joe@chef.io'
license 'all_rights'
description 'Hardneing cookbook for Windows 2012 R2'
long_description 'Remediates critical issues identified by the Windows base profile in Chef Compliance.'
version '0.6.2'
